/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTelegramRouteImport } from './routes/admin.telegram'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminPreviewRouteImport } from './routes/admin.preview'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminKreditkartenRouteImport } from './routes/admin.kreditkarten'
import { Route as AdminElvsRouteImport } from './routes/admin.elvs'
import { Route as AdminTelegramIndexRouteImport } from './routes/admin.telegram.index'
import { Route as AdminShopsIndexRouteImport } from './routes/admin.shops.index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminKreditkartenIndexRouteImport } from './routes/admin.kreditkarten.index'
import { Route as AdminElvsIndexRouteImport } from './routes/admin.elvs.index'
import { Route as AdminShopsNewRouteImport } from './routes/admin.shops.new'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AdminShopsIdEditRouteImport } from './routes/admin.shops.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelegramRoute = AdminTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreviewRoute = AdminPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKreditkartenRoute = AdminKreditkartenRouteImport.update({
  id: '/kreditkarten',
  path: '/kreditkarten',
  getParentRoute: () => AdminRoute,
} as any)
const AdminElvsRoute = AdminElvsRouteImport.update({
  id: '/elvs',
  path: '/elvs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelegramIndexRoute = AdminTelegramIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTelegramRoute,
} as any)
const AdminShopsIndexRoute = AdminShopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShopsRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminKreditkartenIndexRoute = AdminKreditkartenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminKreditkartenRoute,
} as any)
const AdminElvsIndexRoute = AdminElvsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminElvsRoute,
} as any)
const AdminShopsNewRoute = AdminShopsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminShopsRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminShopsIdEditRoute = AdminShopsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminShopsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/elvs': typeof AdminElvsRouteWithChildren
  '/admin/kreditkarten': typeof AdminKreditkartenRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/admin/telegram': typeof AdminTelegramRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/shops/new': typeof AdminShopsNewRoute
  '/admin/elvs/': typeof AdminElvsIndexRoute
  '/admin/kreditkarten/': typeof AdminKreditkartenIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/shops/': typeof AdminShopsIndexRoute
  '/admin/telegram/': typeof AdminTelegramIndexRoute
  '/admin/shops/$id/edit': typeof AdminShopsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/shops/new': typeof AdminShopsNewRoute
  '/admin/elvs': typeof AdminElvsIndexRoute
  '/admin/kreditkarten': typeof AdminKreditkartenIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/shops': typeof AdminShopsIndexRoute
  '/admin/telegram': typeof AdminTelegramIndexRoute
  '/admin/shops/$id/edit': typeof AdminShopsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/elvs': typeof AdminElvsRouteWithChildren
  '/admin/kreditkarten': typeof AdminKreditkartenRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/admin/telegram': typeof AdminTelegramRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/shops/new': typeof AdminShopsNewRoute
  '/admin/elvs/': typeof AdminElvsIndexRoute
  '/admin/kreditkarten/': typeof AdminKreditkartenIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/shops/': typeof AdminShopsIndexRoute
  '/admin/telegram/': typeof AdminTelegramIndexRoute
  '/admin/shops/$id/edit': typeof AdminShopsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/elvs'
    | '/admin/kreditkarten'
    | '/admin/orders'
    | '/admin/preview'
    | '/admin/shops'
    | '/admin/telegram'
    | '/admin/'
    | '/admin/orders/$id'
    | '/admin/shops/new'
    | '/admin/elvs/'
    | '/admin/kreditkarten/'
    | '/admin/orders/'
    | '/admin/shops/'
    | '/admin/telegram/'
    | '/admin/shops/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/preview'
    | '/admin'
    | '/admin/orders/$id'
    | '/admin/shops/new'
    | '/admin/elvs'
    | '/admin/kreditkarten'
    | '/admin/orders'
    | '/admin/shops'
    | '/admin/telegram'
    | '/admin/shops/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/elvs'
    | '/admin/kreditkarten'
    | '/admin/orders'
    | '/admin/preview'
    | '/admin/shops'
    | '/admin/telegram'
    | '/admin/'
    | '/admin/orders/$id'
    | '/admin/shops/new'
    | '/admin/elvs/'
    | '/admin/kreditkarten/'
    | '/admin/orders/'
    | '/admin/shops/'
    | '/admin/telegram/'
    | '/admin/shops/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/telegram': {
      id: '/admin/telegram'
      path: '/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AdminTelegramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preview': {
      id: '/admin/preview'
      path: '/preview'
      fullPath: '/admin/preview'
      preLoaderRoute: typeof AdminPreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kreditkarten': {
      id: '/admin/kreditkarten'
      path: '/kreditkarten'
      fullPath: '/admin/kreditkarten'
      preLoaderRoute: typeof AdminKreditkartenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/elvs': {
      id: '/admin/elvs'
      path: '/elvs'
      fullPath: '/admin/elvs'
      preLoaderRoute: typeof AdminElvsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/telegram/': {
      id: '/admin/telegram/'
      path: '/'
      fullPath: '/admin/telegram/'
      preLoaderRoute: typeof AdminTelegramIndexRouteImport
      parentRoute: typeof AdminTelegramRoute
    }
    '/admin/shops/': {
      id: '/admin/shops/'
      path: '/'
      fullPath: '/admin/shops/'
      preLoaderRoute: typeof AdminShopsIndexRouteImport
      parentRoute: typeof AdminShopsRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/kreditkarten/': {
      id: '/admin/kreditkarten/'
      path: '/'
      fullPath: '/admin/kreditkarten/'
      preLoaderRoute: typeof AdminKreditkartenIndexRouteImport
      parentRoute: typeof AdminKreditkartenRoute
    }
    '/admin/elvs/': {
      id: '/admin/elvs/'
      path: '/'
      fullPath: '/admin/elvs/'
      preLoaderRoute: typeof AdminElvsIndexRouteImport
      parentRoute: typeof AdminElvsRoute
    }
    '/admin/shops/new': {
      id: '/admin/shops/new'
      path: '/new'
      fullPath: '/admin/shops/new'
      preLoaderRoute: typeof AdminShopsNewRouteImport
      parentRoute: typeof AdminShopsRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/shops/$id/edit': {
      id: '/admin/shops/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/shops/$id/edit'
      preLoaderRoute: typeof AdminShopsIdEditRouteImport
      parentRoute: typeof AdminShopsRoute
    }
  }
}

interface AdminElvsRouteChildren {
  AdminElvsIndexRoute: typeof AdminElvsIndexRoute
}

const AdminElvsRouteChildren: AdminElvsRouteChildren = {
  AdminElvsIndexRoute: AdminElvsIndexRoute,
}

const AdminElvsRouteWithChildren = AdminElvsRoute._addFileChildren(
  AdminElvsRouteChildren,
)

interface AdminKreditkartenRouteChildren {
  AdminKreditkartenIndexRoute: typeof AdminKreditkartenIndexRoute
}

const AdminKreditkartenRouteChildren: AdminKreditkartenRouteChildren = {
  AdminKreditkartenIndexRoute: AdminKreditkartenIndexRoute,
}

const AdminKreditkartenRouteWithChildren =
  AdminKreditkartenRoute._addFileChildren(AdminKreditkartenRouteChildren)

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminShopsRouteChildren {
  AdminShopsNewRoute: typeof AdminShopsNewRoute
  AdminShopsIndexRoute: typeof AdminShopsIndexRoute
  AdminShopsIdEditRoute: typeof AdminShopsIdEditRoute
}

const AdminShopsRouteChildren: AdminShopsRouteChildren = {
  AdminShopsNewRoute: AdminShopsNewRoute,
  AdminShopsIndexRoute: AdminShopsIndexRoute,
  AdminShopsIdEditRoute: AdminShopsIdEditRoute,
}

const AdminShopsRouteWithChildren = AdminShopsRoute._addFileChildren(
  AdminShopsRouteChildren,
)

interface AdminTelegramRouteChildren {
  AdminTelegramIndexRoute: typeof AdminTelegramIndexRoute
}

const AdminTelegramRouteChildren: AdminTelegramRouteChildren = {
  AdminTelegramIndexRoute: AdminTelegramIndexRoute,
}

const AdminTelegramRouteWithChildren = AdminTelegramRoute._addFileChildren(
  AdminTelegramRouteChildren,
)

interface AdminRouteChildren {
  AdminElvsRoute: typeof AdminElvsRouteWithChildren
  AdminKreditkartenRoute: typeof AdminKreditkartenRouteWithChildren
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPreviewRoute: typeof AdminPreviewRoute
  AdminShopsRoute: typeof AdminShopsRouteWithChildren
  AdminTelegramRoute: typeof AdminTelegramRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminElvsRoute: AdminElvsRouteWithChildren,
  AdminKreditkartenRoute: AdminKreditkartenRouteWithChildren,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPreviewRoute: AdminPreviewRoute,
  AdminShopsRoute: AdminShopsRouteWithChildren,
  AdminTelegramRoute: AdminTelegramRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
