/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminShopsIndexRouteImport } from './routes/admin.shops.index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminShopsNewRouteImport } from './routes/admin.shops.new'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AdminShopsIdEditRouteImport } from './routes/admin.shops.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopsIndexRoute = AdminShopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShopsRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminShopsNewRoute = AdminShopsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminShopsRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminShopsIdEditRoute = AdminShopsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminShopsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/shops/new': typeof AdminShopsNewRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/shops/': typeof AdminShopsIndexRoute
  '/admin/shops/$id/edit': typeof AdminShopsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/shops/new': typeof AdminShopsNewRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/shops': typeof AdminShopsIndexRoute
  '/admin/shops/$id/edit': typeof AdminShopsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/shops/new': typeof AdminShopsNewRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/shops/': typeof AdminShopsIndexRoute
  '/admin/shops/$id/edit': typeof AdminShopsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/orders'
    | '/admin/shops'
    | '/admin/'
    | '/admin/orders/$id'
    | '/admin/shops/new'
    | '/admin/orders/'
    | '/admin/shops/'
    | '/admin/shops/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/orders/$id'
    | '/admin/shops/new'
    | '/admin/orders'
    | '/admin/shops'
    | '/admin/shops/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/orders'
    | '/admin/shops'
    | '/admin/'
    | '/admin/orders/$id'
    | '/admin/shops/new'
    | '/admin/orders/'
    | '/admin/shops/'
    | '/admin/shops/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops/': {
      id: '/admin/shops/'
      path: '/'
      fullPath: '/admin/shops/'
      preLoaderRoute: typeof AdminShopsIndexRouteImport
      parentRoute: typeof AdminShopsRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/shops/new': {
      id: '/admin/shops/new'
      path: '/new'
      fullPath: '/admin/shops/new'
      preLoaderRoute: typeof AdminShopsNewRouteImport
      parentRoute: typeof AdminShopsRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/shops/$id/edit': {
      id: '/admin/shops/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/shops/$id/edit'
      preLoaderRoute: typeof AdminShopsIdEditRouteImport
      parentRoute: typeof AdminShopsRoute
    }
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminShopsRouteChildren {
  AdminShopsNewRoute: typeof AdminShopsNewRoute
  AdminShopsIndexRoute: typeof AdminShopsIndexRoute
  AdminShopsIdEditRoute: typeof AdminShopsIdEditRoute
}

const AdminShopsRouteChildren: AdminShopsRouteChildren = {
  AdminShopsNewRoute: AdminShopsNewRoute,
  AdminShopsIndexRoute: AdminShopsIndexRoute,
  AdminShopsIdEditRoute: AdminShopsIdEditRoute,
}

const AdminShopsRouteWithChildren = AdminShopsRoute._addFileChildren(
  AdminShopsRouteChildren,
)

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminShopsRoute: typeof AdminShopsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminShopsRoute: AdminShopsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
